### PR TITLE
Add Vagrant environment

### PR DESCRIPTION
**Pull request by ymkins**
There is the Vagrant environment for quick start with loraserver infrastructure.
Just install VirtualBox and Vagrant and got Ubuntu based virtual machine with Docker containers and all loraserver components built from source.

### CODE REVIEW

**Comment by brocaar** [comment]
Hi @ymkins thanks for your work! A while ago I've been working on a set of Ansible scripts (https://github.com/brocaar/loraserver-setup). This needs some more love and might not be completely up-to-date with the latest version. Ideally I would move the `Vagrantfile` to there, and then provision the Vagrant box using the [ansible_local](https://www.vagrantup.com/docs/provisioning/ansible_local.html) provisioner. That way the playbooks can be used for both local environments and (multi-server) deployments. What do you think?

**Comment by ymkins** [comment]
@brocaar
yes, it would be great

**Comment by brocaar** [comment]
Just a small update. I'm looking into packaging all services into `.deb` packages (might be extended to `.rpm` in the future). This will not only make deployments much easier, but will reduce the steps needed for setting up a Vagrant environment :-)

**Comment by brocaar** [comment]
See #115

**Comment by brocaar** [comment]
Hi @ymkins do you mind when I close this pull request in favor of https://github.com/brocaar/loraserver-setup? I redid the complete Ansible playbook so that it uses the deb repository (https://repos.loraserver.io) and so that it can be used for both Vagrant and normal deployments (e.g. AWS, DigitalOcean, bare-metal, etc...).

**Comment by ymkins** [comment]
@brocaar, yes, it makes sense.

**Pull request closed without merging**
