### PR TITLE
Add option to disable adr for loraserver

### PR DESCRIPTION
**Pull request by iegomez**
This PR was discussed here: https://forum.loraserver.io/t/can-you-disable-server-side-adr/1009/8
It's a useful feature as some lora modules (such as RN2903) have bugs concerning ADR, where they'll randomly set it to true despite of receiving adr false command.

### CODE REVIEW

**Comment by iegomez** [comment]
I'll have to give it another look to pass the tests, but can't do it till tuesday.

**Comment by brocaar** [comment]
Hi @iegomez thanks! However I understood that this would be a config flag, like the disable mac-commands flag (https://forum.loraserver.io/t/testing-the-upcoming-lora-app-server-v2-release/1610/4):

```toml
  # Disable mac-commands
  #
  # When set, uplink mac-commands are ignored and the network-server will not
  # send mac-commands to the devices. This is intended for testing only.
  disable_mac_commands=false
```

https://github.com/brocaar/loraserver/blob/master/docs/content/install/config.md

I don't think it is a good idea to include this into the device-profile. The device already has an option to turn ADR on or off using the `adr` bit on uplink. I know that Microchip has a bug (which is open since a long time) which enables ADR when the device receives a downlink mac-command (any). However it should not be the responsibility of LoRa Server to fix this.

From a network-server domain however it makes sense to have control to system-wide enable or disable ADR. Therefore I prefer the ADR flag in the `loraserver.toml` config file instead of adding this to the device-profile (also since currently it follows the device-profile fields as specified by the LoRaWAN Backend Interface specification document: https://lora-alliance.org/lorawan-for-developers).

Also note that the device-profile represents fields prescribing the boot-state of a device. E.g. how it was provisioned when it came out of the factory. When the RX delay is set to 5 in the device-profile and 1 in `loraserver.toml`, this means that LoRa Server will respect the device-profile until it has updated the device to reflect the `loraserver.toml` configuration (using mac-commands).

**Comment by iegomez** [comment]
Hi, Orne. I'm terribly sorry, I pushed the device profile option by mistake, but I didn't really intend to add it to the proposed solution. The original solution and what I wanted to submit only included the disable_adr flag as a global option. I'll fix it tomorrow, check the tests and push it again.

**Comment by iegomez** [comment]
It's fixed now: I removed the wrong commit and tests are passing ok.

**Pull request merged**
