### PR TITLE
Master

### PR DESCRIPTION
**Pull request by Eliatrope38**
add Multitech procedure for joining LoraServer

### CODE REVIEW

**Comment by brocaar** [comment]
Hi @Eliatrope38, thanks for your pull-request 👍 Could you add the command for the `DevEUI` as well, I think it is missing (you're configuring the `AppEUI` and the `AppKey`)?

**Comment by Eliatrope38** [comment]
Hello Orne

no need to configure it . It's a factory programmed setting.

"All mDots have a factory-programmed Extended Unique Identifier (EUI). This
is Marked as Node on the mDot label"

If you want I can add a comment

Thank you
David


2016-08-15 19:23 GMT+02:00 Orne Brocaar <notifications@github.com>:

**Comment by brocaar** [comment]
Yes, I think that is a good idea. Since in the beginning of the page, some example values are defined which are used for all the examples.

**Comment by brocaar** [comment]
Thanks! I've merged your changes. Please note that it might take some time before Cloudfront will expire its cache and your change will be visible.

**Pull request merged**
